name: "build"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '14' ]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Run docker
        run: |
          cd db-migration
          cp .env.example .env
          chmod +x *.sh
          ./build.sh
          ./download.sh
          ./start.sh
      - name: Build
        run: |
          cd db-migration
          chmod +x ./gradlew
          ./gradlew
      - name: Stop docker
        run: |
          cd db-migration
          ./stop.sh
